stages:
  - tag

semantic_release:
  stage: tag
  image: node:latest
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
  before_script:
    - npm install -g semantic-release @semantic-release/gitlab-config
  script:
    - semantic-release -e @semantic-release/gitlab-config
  only:
    - master
